name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.EC2_HOST }}
      USERNAME: ${{ secrets.EC2_USER }}
      KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PORT: ${{ secrets.EC2_PORT }}
      APP_DIRECTORY: ${{ secrets.EC2_APP_DIRECTORY }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Build project
        run: yarn run build

      - name: Copy package.json
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.EC2_PORT }}
          source: ./package.json
          target: ${{ env.EC2_APP_DIRECTORY }}

      - name: Copy files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.EC2_PORT }}
          source: ./dist/*
          target: ${{ env.EC2_APP_DIRECTORY }}

      - name: Run service in EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.EC2_PORT }}
          script: |
            cd ${{ env.EC2_APP_DIRECTORY }}
            yarn install --frozen-lockfile --production
            pm2 restart all || pm2 start dist/src/main.js --name "tasks-nestjs"
