name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set up yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Build project
        run: yarn run build

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{secrets.EC2_HOST}}
          EC2_USER: ${{secrets.SSH_HOST}}
          EC2_APP_DIRECTORY: ${{secrets.EC2_APP_DIRECTORY}}
        run: |
          echo "$EC2_HOST"
          echo "$EC2_USER"
          echo "$EC2_APP_DIRECTORY"
          echo "$PRIVATE_KEY" > private_key.pem && chmod 400 private_key.pem
          scp -i private_key.pem -r ./package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_APP_DIRECTORY }}
          scp -i private_key.pem -r ./dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_APP_DIRECTORY }}
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s' << 'EOF'
          cd ${{ secrets.EC2_APP_DIRECTORY }}
          yarn install --production
          yarn run start:prod
          EOF
